victoria-metrics-k8s-stack:
  grafana-dashboards:
    enabled: false
  defaultDashboardsEnabled: false

  grafana:
    enabled: true
    defaultDashboardsEnabled: false
    dashboardProviders: {}
    dashboardsConfigMaps: []

  prometheus-node-exporter:
    dashboards:
      enabled: false

  vmagent:
    enabled: true
    additionalScrapeConfigs:
      - job_name: "spam2000"
        static_configs:
          - targets:
              - "spam2000.monitoring.svc.cluster.local:8080"
