victoria-metrics-k8s-stack:
  grafana-dashboards:
    enabled: false
  defaultDashboardsEnabled: false

  grafana:
    enabled: true
    defaultDashboardsEnabled: false
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard

  prometheus-node-exporter:
    dashboards:
      enabled: false

  vmagent:
    enabled: true
